[package]
name = "powerflow"
version = "0.2.2"
description = "Monitoring power usage of mac and iOS devices"
authors = [ "Samuel Lyon" ]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "powerflow_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[features]
# for disabling waring from `objc` crate
default = [ "cargo-clippy" ]
cargo-clippy = []

[build-dependencies]
tauri-build = { version = "2", features = [ "config-toml" ] }

[dependencies]
anyhow = "1"
tpower = { features = [ "specta" ], workspace = true }
tauri = { version = "2", features = [
  "macos-private-api",
  "tray-icon",
  "devtools",
] }
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
tauri-plugin-pinia = "5.0.2"
tauri-plugin-log = "2"
tauri-plugin-nspopover = { path = "../crates/nspopover" }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tokio = { version = "1.42.0", features = [ "full" ] }
specta = { version = "=2.0.0-rc.25", features = [
  "chrono",
  "serde_json"
] }
specta-typescript = "0.0.12"
tauri-specta = { version = "=2.0.0-rc.25", features = [
  "derive",
  "typescript"
] }
strum = { version = "0.28", features = [ "derive" ] }
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
log = "0.4.22"
thiserror = "2.0.9"
scopefn = "0.0.2"
sqlx = { version = "0.9.0", default-features = false, features = [
  "chrono",
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate"
] }
chrono = { version = "0.4.39", features = [ "serde" ] }
derive_more = { version = "2.1.1", features = [ "deref" ] }
tauri-plugin-dialog = "2"
