[package]
name = "tpower"
version = "0.2.2"
edition = "2021"

[features]
specta = [
  "dep:specta",
  "dep:specta-typescript"
]

[dependencies]
core-foundation = "0.10.0"
libc = "0.2.168"
mach = { package = "mach2", version = "0.7" }
thiserror = "2.0.6"
log = "0.4.22"
io-kit-sys = "0.5"
anyhow = "1.0.94"
plist = "1.7.0"
serde = { version = "1.0.216", features = [ "derive" ] }
specta = { optional = true, version = "=2.0.0-rc.25", features = [
  "serde_json",
  "derive",
] }
specta-typescript = { optional = true, version = "0.0.12" }
derive_more = { version = "2.1.1", features = [
  "add",
  "mul"
] }
